name: Test-Coverage

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///db.sqlite3
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          make test
          make test-coverage

      - name: Run code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          DATABASE_URL: sqlite:///db.sqlite3
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          coverageCommand: make test-coverage
          debug: true